# Generated by Django 2.1.15 on 2022-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Fresh_Small', 'Fresh_Small'), ('Fresh_Medium', 'Fresh_Medium'), ('Fresh_Large', 'Fresh_Large'), ('Frozen_Small', 'Frozen_Small'), ('Frozen_Medium', 'Frozen_Medium'), ('Frozen_Large', 'Frozen_Large'), ('Fresh_Gutted_&_Scaled_Small', 'Fresh_Gutted_&_Scaled_Small'), ('Fresh_Gutted_&_Scaled_Medium', 'Fresh_Gutted_&_Scaled_Medium'), ('Fresh_Gutted_&_Scaled_Large', 'Fresh_Gutted_&_Scaled_Large'), ('Frozen_Gutted_&_Scaled_Small', 'Frozen_Gutted_&_Scaled_Small'), ('Frozen_Gutted_&_Scaled_Medium', 'Frozen_Gutted_&_Scaled_Medium'), ('Frozen_Gutted_&_Scaled_Large', 'Frozen_Gutted_&_Scaled_Large'), ('Smoked', 'Smoked'), ('Ice_bag', 'Ice_bag')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(choices=[('Tilapia', 'Tilapia'), ('Ice', 'Ice')], max_length=100, null=True),
        ),
    ]
