# Generated by Django 2.1.15 on 2022-11-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0002_auto_20221121_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
