# Generated by Django 2.1.15 on 2022-11-21 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0004_auto_20221121_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='area_sales_manager',
            field=models.CharField(choices=[('Mwangala', 'Mwangala'), ('Geofrey', 'Geofrey'), ('Diana', 'Diana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Modern Trade', 'Modern Trade'), ('Horeca', 'Horeca'), ('Export', 'Export'), ('Yalelo Store', 'Yalelo Store')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='distribution_center',
            field=models.CharField(choices=[('Lusaka', 'Lusaka'), ('Kitwe', 'Kitwe')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_Mix',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Dynamic', 'Dynamic')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.CharField(choices=[('North OTD', 'North OTD'), ('South East', 'South East'), ('Central', 'Central'), ('West', 'West')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
