# Generated by Django 2.1.15 on 2022-11-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0006_auto_20221121_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
